### ISSUE TITLE
net-core to-do list

### ISSUE THREAD

**Issue by juanjp600** [juanjp600/cbre#31]
- [x] Tweakable FOV
- [x] Floating texture selection window
- [x] Tool defaults
- [ ] Prop path selection
- [ ] Prop baking
- [ ] Alpha depth sorting
- [x] Fix lightmap UV half-luxel error
- [ ] Radiosity
- [ ] ??????

**Comment by waffles187** [comment]
- [x] Z hotkey to toggle mouselook
- [x] Cursor not hidden during mouselook
- [x] Recently edited maps in the file menu
- [ ] Lightmap resolution option on texture tool
- [x] Shift + drag duplicates the selection twice
- [x] Key binds ignoring ctrl / alt / shift (3D view moving backwards when pressing ctrl + S / mouselook when trying to ctrl + Z)
- [x] Width and height measurements not showing on selection in 2D view
- [x] The ignore grouping button works independently to ctrl + W
- [ ] Paste special (ctrl + shift + V) causes an exception
- [ ] Texture tool is tedious to use (clicking apply each time a value is changed + justify buttons missing)
- [x] Hiding objects does not visually hide the object
